modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/xaidee/Zombie-Friends/issues/"
license="The MIT License (MIT)"

[[mods]]
modId="zombiefriends"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime
version="${file.jarVersion}"
displayName="Zombie Friends"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/zombie-friends"
logoFile="banner.png"
logoBlur=false
itemIcon="minecraft:zombie_head"
configBackground="minecraft:textures/block/stone_bricks.png"
credits="Team Galena"
authors="Xaidee Quartz"
description='''
A small mod that adds texture variants for all the new default skins added by Mojang. They will be randomly applied to spawned Zombies but can be manually changed using nametags!
'''

[[dependencies.zombiefriends]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zombiefriends]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.20)"
    ordering="NONE"
    side="BOTH"
